Repository wp-cli/wp-cli-tests, pull requests merged in 2018-08, with the labels that each got.

#7 Use realpath() when comparing paths
  features/steps/given.php
Labels: bug, scope:testing

#9 Run both PHPUnit bootstrap files
  bin/run-php-unit-tests
  bin/run-phpcs-tests
  tests/bootstrap.php
Labels: scope:testing

#10 Make features folder configurable in behat-tags.php
  utils/behat-tags.php
Labels: scope:testing

#11 Add default to WP_VERSION to avoid empty var bug
  bin/run-behat-tests
Labels: scope:testing

#16 Explain how to re-run failed scenarios
  .travis.yml
  README.md
Labels: scope:documentation, scope:testing

#19 Fix fetching the VERSION file from the framework
  tests/bootstrap.php
Labels: bug, scope:testing

#21 Remove erroneous define from PHPUnit bootstrap
  tests/bootstrap.php
Labels: bug, scope:testing

#23 Add `Given a ... cache file` step
  features/steps/given.php
Labels: scope:testing
