Repository wp-cli/wp-cli-tests, pull requests merged in 2018-12, with the labels that each got.

#32 Adapt the README.md partial
  .readme-partials/USING.md
Labels: scope:documentation

#31 [WIP] Make it easier to write tests for WordPress plugins containing CLI commands
  features/bootstrap/FeatureContext.php
  features/steps/given.php
Labels: scope:testing

#33 Fix/required dependency version
  composer.json
Labels: scope:distribution

#35 PHPCompatibilityWP: update to use version ^2
  composer.json
  phpcs.xml.dist
Labels: scope:testing
