Repository wp-cli/wp-cli-tests, pull requests merged in 2019-04, with the labels that each got.

#50 Move PHP 5.4 tests from `WP_VERSION` `latest` to `5.1`
  .travis.yml
Labels: scope:distribution

#52 PHPCS: fix up the code base [10] - rename a local variable
  features/bootstrap/utils.php
Labels: scope:testing

#54 Use strict comparisons
  features/steps/then.php
Labels: scope:testing

#53 Wrap Behat & PHPUnit bootstrapping code into a function
  features/bootstrap/FeatureContext.php
  tests/bootstrap.php
Labels: scope:testing

#55 Adapt variable names to move from camelCase to snake_case
  features/bootstrap/support.php
  features/steps/then.php
Labels: scope:testing

#57 Add `CODEOWNERS` file
  .github/CODEOWNERS
Labels: scope:testing

#58 Prefix functions in global namespace
  features/steps/when.php
Labels: scope:testing

#59 Use snake_case for support functions and put them under a namespace
  features/bootstrap/support.php
  features/steps/then.php
Labels: scope:testing

#44 Create a `WP_CLI_CS` standard for PHP_CodeSniffer
  .distignore
  .gitignore
  .readme-partials/USING.md
  WP_CLI_CS/ruleset.xml
  bin/run-phpcs-tests
  composer.json
  features/bootstrap/support.php
  features/extra/no-mail.php
  phpcs.xml.dist
  tests/bootstrap.php
Labels: scope:testing

#60 Use correct number of `dirname()` calls to find the `vendor` folder
  features/bootstrap/FeatureContext.php
Labels: bug, scope:testing

#61 Fix return code comparisons
  features/steps/then.php
Labels: bug

#62 Travis: Add QA-checks for the WP_CLI_CS ruleset
  .travis.yml
  WP_CLI_CS/ruleset.xml
Labels: scope:testing

#63 Always show sniff name in addition to error message
  phpcs.xml.dist
Labels: scope:testing

#64 Fix ID comparison
  features/bootstrap/FeatureContext.php
Labels: bug, scope:testing
