Repository wp-cli/wp-cli-tests, pull requests merged in 2019-11, with the labels that each got.

#71 Fix MySQL8 column-statistics compatibility issue
  features/bootstrap/FeatureContext.php
Labels: bug, scope:testing

#72 Add polyfill for `get_theme_file_uri()`
  features/bootstrap/FeatureContext.php
  features/bootstrap/support.php
  features/extra/polyfills.php
  phpcs.xml.dist
Labels: scope:testing

#74 Exclude rules that disallow short array syntax & short ternaries
  WP_CLI_CS/ruleset.xml
Labels: scope:testing

#75 Only create mu-plugins dir if it doesn't exist
  features/bootstrap/FeatureContext.php
Labels: bug, scope:testing

#76 Add is_customize_preview() polyfill
  features/extra/polyfills.php
Labels: breaking-change, scope:testing

#77 Fix typo
  .readme-partials/USING.md
  README.md
Labels: bug, scope:documentation
