Repository wp-cli/wp-cli-tests, pull requests merged in 2020-06, with the labels that each got.

#87 Update install-package-tests
  bin/install-package-tests
Labels: scope:testing

#88 Fix password variable
  bin/install-package-tests
Labels: bug, scope:testing

#91 Composer: update PHPCS Composer plugin dependency
  composer.json
Labels: scope:distribution, scope:testing
