Repository wp-cli/wp-cli-tests, pull requests merged in 2021-11, with the labels that each got.

#137 Use latest branch for Roave security advisories
  composer.json
Labels: scope:distribution

#136 Include `WP_CLI_ALLOW_ROOT` in process env variables
  src/Context/FeatureContext.php
Labels: scope:testing

#138 Improve Behat binaries
  bin/rerun-behat-tests
  bin/run-behat-tests
Labels: bug, scope:testing
