Repository wp-cli/wp-cli-tests, pull requests merged in 2023-04, with the labels that each got.

#165 Fix PHP 8.2 deprication warnings
  src/Context/FeatureContext.php
Labels: bug

#166 Avoid error when using `composer behat -- --help`
  bin/run-behat-tests
Labels: bug, scope:testing

#167 Update install-package-tests to wait until MySQL is ready to accept connections
  bin/install-package-tests
Labels: scope:testing

#168 Use POSIX-compatible counter incrementing
  bin/install-package-tests
Labels: scope:testing
