Repository wp-cli/wp-cli-tests, pull requests merged in 2023-10, with the labels that each got.

#180 Look into `getcwd()` first when searching for vendor folder
  src/Context/FeatureContext.php
Labels: bug, scope:testing

#183 In `copy_dir()`, use `cp -R` on Mac, `cp -r` everywhere else
  src/Context/FeatureContext.php
Labels: scope:testing

#186 Fix readme
  .readme-partials/USING.md
Labels: scope:documentation

#187 SQLite: fix `wp-config.php` creation
  features/testing.feature
  src/Context/FeatureContext.php
Labels: scope:testing
